# Generated by Django 3.2.3 on 2021-06-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210615_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudobra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
