# Generated by Django 3.2.3 on 2021-06-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitudobra_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaObras',
            new_name='CategoriaObra',
        ),
        migrations.RenameModel(
            old_name='solicitudObra',
            new_name='Obra',
        ),
        migrations.DeleteModel(
            name='obrasPublicadas',
        ),
        migrations.DeleteModel(
            name='solicitudesContacto',
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='idSolicitudObra',
            new_name='idObra',
        ),
    ]
